### ISSUE TITLE
New Patches Logo to replace Vizor -logo

### ISSUE THREAD

**Issue by esaruoho** [vizorvr/patches#2021]
here's the @mattatgit -created Patches Logo that is supposed to replace the current Vizor Logo in the Editor.

[Patches_wordmark.svg.zip](https://github.com/vizorvr/vizor/files/1126986/Patches_wordmark.svg.zip)

**Comment by esaruoho** [comment]
![screen shot 2017-07-06 at 13 59 56](https://user-images.githubusercontent.com/4966687/27912121-68924376-6264-11e7-8c7c-218da2c9b68c.png)

**Comment by mattatgit** [comment]
i'd drop the "from Vizor" and vertically centre the Patches wordmark the way the Vizor wordmark was setup. @esaruoho

**Comment by esaruoho** [comment]
![vizor_patches](https://user-images.githubusercontent.com/4966687/30014581-b2035a8e-9155-11e7-9f7a-ce38a36f70e1.png)

Closing ticket as Patches-logo is there. Opening a secondary ticket to center the Patches wordmark.
