### ISSUE TITLE
360 video rendering?

### ISSUE THREAD

**Issue by brylie** [vizorvr/patches#2049]
Is it possible, or planned, to be able to render 360 video in a patches scene?

**Comment by esaruoho** [comment]
Hi @brylie, you check out this example - https://patches.vizor.io/examples/360video and edit it (or directly go to https://patches.vizor.io/examples/360video/edit to edit) - replace the Video Source with your file of choice (we recommend the most universal .M4V -format)

Ho live-streaming is unfortunately possible - static uploaded file only, but we hope you will enjoy testing out 360 video in a Patches project!

**Comment by brylie** [comment]
Thanks for the quick reply.

Also, greetings from Tampere!

**Comment by brylie** [comment]
@esaruoho thanks again for your earlier response.

I am just trying again to add a **360 video player**, as per the article [Using 360 Video in your Patches Project](http://blog.vizor.io/using-360-video-in-your-patches-project/), but cannot find one. All I see is a video player, which does not seem to work as intended for 360 videos.

**Comment by esaruoho** [comment]
Hi @brylie - thanks for checking out the tutorial! it is always best to check out the template created for the tutorial, which in this case is linked in the article.

the link is: http://patches.vizor.io/examples/360-video/edit

this will take you directly into editing of the 360-video template. Please hit me up on our http://vizorvr.herokuapp.com url (i'm @esaruoho there) if you have any other details you'd like to figure out.

Enjoy!
